# Generated by Django 4.1.4 on 2022-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaApp', '0002_customer_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='batch',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
