# Generated by Django 4.1.4 on 2022-12-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaApp', '0003_alter_customer_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_time',
        ),
    ]
